sonar.projectKey=playwright-ui-api-framework
sonar.projectName=Playwright UI API Framework
sonar.projectVersion=1.0

# Local SonarQube server
sonar.host.url=http://localhost:9000

# Read token from environment (PowerShell: $env:SONAR_TOKEN="...")
sonar.token=${env.SONAR_TOKEN}

# For SonarCloud only, uncomment and set your real organization key:
# sonar.organization=your-sonarcloud-organization
sonar.sourceEncoding=UTF-8

sonar.sources=pages,helpers,utils,tests
sonar.tests=tests
sonar.test.inclusions=tests/**/*.spec.ts,tests/**/*.test.ts

sonar.exclusions=node_modules/**,playwright-report/**,test-results/**,allure-results/**,allure-report/**,coverage/**,playwright/.auth/**

# Optional: enable when coverage report exists
sonar.javascript.lcov.reportPaths=coverage/lcov.info
